"""baseline: esquema inicial

Revision ID: fcd983da6444
Revises: 
Create Date: 2026-08-17 21:46:56.538155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcd983da6444'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encargado_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('horas_seguimiento', sa.Integer(), nullable=False),
    sa.Column('max_seguimientos', sa.Integer(), nullable=False),
    sa.Column('mensaje_seguimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instance_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apikey', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_activo', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ultimo_mensaje', sa.DateTime(), nullable=True),
    sa.Column('seguimientos', sa.Integer(), nullable=False),
    sa.Column('listo_para_cerrar', sa.Boolean(), nullable=False),
    sa.Column('notas_encargado', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('tipo_inmueble', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('zona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superficie_m2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('intencion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_lead_id'), 'leads', ['lead_id'], unique=True)
    op.create_index(op.f('ix_leads_whatsapp'), 'leads', ['whatsapp'], unique=True)
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_whatsapp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_lead_whatsapp'), 'mensajes', ['lead_whatsapp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_lead_whatsapp'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_leads_whatsapp'), table_name='leads')
    op.drop_index(op.f('ix_leads_lead_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('company_info')
    op.drop_table('bot_config')
    # ### end Alembic commands ###
